
DROP TABLE IF EXISTS 'JOUEUR' ;
CREATE TABLE IF NOT EXISTS 'JOUEUR' (
  idJoueur INT() NOT NULL,
  pseudoJoueur VARCHAR(),
  PRIMARY KEY (idJoueur)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'CASE' ;
CREATE TABLE IF NOT EXISTS 'CASE' (
  idCase INT() NOT NULL,
  x INT(), 
  y INT(),
  PRIMARY KEY (idCase)
)ENGINE = InnoDB;

DROP TABLE IF EXISTS 'RESSOURCE';
CREATE TABLE IF NOT EXISTS 'RESSOURCE'(
  idRessource INT() NOT NULL,
  nomRessource VARCHAR(),
  PRIMARY KEY (idRessource)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'UNITE';
CREATE TABLE IF NOT EXISTS 'UNITE'(
  idUnite INT() NOT NULL,
  nomUnite VARCHAR(),
  PRIMARY KEY (idUnite)
)ENGINE = InnoDB;


#____________________________

DROP TABLE IF EXISTS 'TYPE';
CREATE TABLE IF NOT EXISTS 'TYPE'(
  idType INT() NOT NULL,
  nomType VARCHAR(),
  PRIMARY KEY (idType)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'BATIMENT';
CREATE TABLE IF NOT EXISTS 'BATIMENT'(
  idBatiment INT() NOT NULL,
  nomBatiment VARCHAR(),
  idType INT(),
  CONSTRAINT FOREIGN KEY idType REFERENCES TYPE(idType) ON DELETE CASCADE,
  PRIMARY KEY (idBatiment)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'TECHNOLOGIE';
CREATE TABLE IF NOT EXISTS 'TECHNOLOGIE'(
  idTech INT() NOT NULL,
  nomTech VARCHAR(),
  PRIMARY KEY (idTech)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'EST_INSTALLE';
CREATE TABLE IF NOT EXISTS 'EST_INSTALLE'(
  CONSTRAINT FOREIGN KEY idJoueur REFERENCES JOUEUR ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idCase REFERENCES CASE ON DELETE CASCADE,
  PRIMARY KEY(idJoueur, idCase)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'POSSEDE_BATIMENT';
CREATE TABLE IF NOT EXISTS 'POSSEDE_BATIMENT'(
  CONSTRAINT FOREIGN KEY idJoueur REFERENCES JOUEUR ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idBatiment REFERENCES BATIMENT ON DELETE CASCADE,
  PRIMARY KEY(idJoueur, idBatiment)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'POSSEDE_UNITE';
CREATE TABLE IF NOT EXISTS 'POSSEDE_UNITE'(
  CONSTRAINT FOREIGN KEY idJoueur REFERENCES JOUEUR ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idUnite REFERENCES UNITE ON DELETE CASCADE,
  PRIMARY KEY(idJoueur, idUnite)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'CONNAIT';
CREATE TABLE IF NOT EXISTS 'CONNAIT'(
  CONSTRAINT FOREIGN KEY idJoueur REFERENCES JOUEUR ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idTech REFERENCES TECHNOLOGIE ON DELETE CASCADE,
  PRIMARY KEY(idJoueur, idTech)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'POSSEDE_RESSOURCE';
CREATE TABLE IF NOT EXISTS 'POSSEDE_RESSOURCE'(
  quantiteRess INT(),
  CONSTRAINT FOREIGN KEY idJoueur REFERENCES JOUEUR(idJoueur) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idRessource REFERENCES RESSOURCE(idRessource) ON DELETE CASCADE,
  PRIMARY KEY(idJoueur, idRessource)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'ATTAQUE';
CREATE TABLE IF NOT EXISTS 'ATTAQUE'(
  puissance INT(),
  tempsAttaque INT(),
  CONSTRAINT FOREIGN KEY idAttaquant REFERENCES JOUEUR(idJoueur) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idDefenseur REFERENCES JOUEUR(idJoueur) ON DELETE CASCADE,
  PRIMARY KEY(tempsAttaque, idAttaquant, idDefenseur)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'PRODUIT_UNITE';
CREATE TABLE IF NOT EXISTS 'PRODUIT_UNITE'(
  quantite INT(),
  idUnite INT(),
  idBatiment INT(),
  CONSTRAINT FOREIGN KEY idUnite REFERENCES UNITE(idUnite) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idBatiment REFERENCES BATIMENT(idBatiment) ON DELETE CASCADE,
  PRIMARY KEY(idUnite, idBatiment)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'COUTE_BATIMENT';
CREATE TABLE IF NOT EXISTS 'COUTE_BATIMENT'(
  quantite INT(),
  idRessource INT(),
  idBatiment INT(),
  CONSTRAINT FOREIGN KEY idRessource REFERENCES RESSOURCE(idRessource) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idBatiment REFERENCES BATIMENT(idBatiment) ON DELETE CASCADE,
  PRIMARY KEY(idRessource, idBatiment)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'UPGRADE';
CREATE TABLE IF NOT EXISTS 'UPGRADE'(
  idBatiment INT(),
  idUpgrade INT(),
  CONSTRAINT FOREIGN KEY idBatiment REFERENCES BATIMENT(idBatiment) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idUpgrade REFERENCES BATIMENT(idUpgrade) ON DELETE CASCADE,
  PRIMARY KEY(idBatiment, idUpgrade)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'PRODUIT_RESSOURCE';
CREATE TABLE IF NOT EXISTS 'PRODUIT_RESSOURCE'(
  quantite INT(),
  idRessource INT(),
  idBatiment INT(),
  CONSTRAINT FOREIGN KEY idRessource REFERENCES RESSOURCE(idRessource) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idBatiment REFERENCES BATIMENT(idBatiment) ON DELETE CASCADE,
  PRIMARY KEY(idRessource, idBatiment)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'UPGRADE_DEPEND';
CREATE TABLE IF NOT EXISTS 'UPGRADE_DEP END'(
  idBatiment INT(),
  idTech INT(),
  CONSTRAINT FOREIGN KEY idBatiment REFERENCES BATIMENT(idBatiment) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idTech REFERENCES TECHNOLOGIE(idTech) ON DELETE CASCADE,
  PRIMARY KEY(idBatiment, idTech)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'COUTE_UNITE';
CREATE TABLE IF NOT EXIST 'COUTE_UNITE'(
  idUnite INT(),
  idRessource INT(),
  CONSTRAINT FOREIGN KEY idUnite REFERENCES UNITE(idUnite) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idRessource REFERENCES RESSOURCE(idRessource) ON DELETE CASCADE,
  PRIMARY KEY(idUnite, idRessource)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'UNITE_DEPEND_DE';
CREATE TABLE IF NOT EXISTS 'UNITE_DEPEND_DE'(
  idUnite INT(),
  idTech INT(),
  CONSTRAINT FOREIGN KEY idUnite REFERENCES UNITE(idUnite) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY idTech REFERENCES TECHNOLOGIE(idTech) ON DELETE CASCADE,
  PRIMARY KEY(idUnite, idTech)
)ENGINE = InnoDB;

#____________________________

DROP TABLE IF EXISTS 'TECH_DEPEND_DE';
CREATE TABLE IF NOT EXISTS 'TECH_DEPEND_DE'(
  techRequis INT(),
  techUpgrade INT(),
  CONSTRAINT FOREIGN KEY techRequis REFERENCES TECHNOLOGIE(idTech) ON DELETE CASCADE,
  CONSTRAINT FOREIGN KEY techUpgrade REFERENCES TECHNOLOGIE(idTech) ON DELETE CASCADE,
  PRIMARY KEY(techRequis, techUpgrade)
)ENGINE = InnoDB;1